language: node_js
node_js:
  - 'stable'

git:
  depth: 5

cache:
  directories:
    - '$HOME/.npm'

matrix:
  fast_finish: true
  include:
    - env:
      before_script:
        - yarn install
      script:
        - yarn test
        - yarn build
